### ISSUE TITLE
Post 상세페이지 template 생성하기

### ISSUE THREAD

**Issue by eonseok-jeon** [eonseok-jeon/eonseok-jeon.github.io#2]
## New Feature
Post 상세페이지 template 생성하기

## Description
Post preview 클릭했을때 들어가지는 post 상세 페이지 UI 구현
공통 component로 분리 및 관리

## Todo
- [x] post 상세페이지 UI 피그마 작성
- [x] 피그마를 토대로 코드 작성
- [x] 공통 component화 하기

## ETC
화이팅 👶🏻
